language = "C"

cpp_compat = true
include_guard = "_WARP_RG_IPFS_H_"

[export]

exclude = ["FFIError", "FFIResult_Null"]

[parse]
parse_deps = true
clean = false
include = ["warp"]

[parse.expand]
crates = ["warp", "warp-rg-ipfs"]
