[package]
name = "warp-mp-ipfs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib", "staticlib"]

[dependencies]
warp = { path = "../../warp" }

ipfs = { git = "https://github.com/Satellite-im/rust-ipfs", branch = "libp2p-next-usable", features = ["external-gossipsub-stream"]}
libp2p = { default-features = false, version = "0.48" }
libipld = { version = "0.13", features = ["serde-codec"] }
uuid = { version = "1.0", features = ["serde", "v4"] }
tokio = { version = "1", features = ["full"] }
futures = { version = "0.3" }
async-trait = { version = "0.1" }
anyhow = { version = "1" }
thiserror = "1.0"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = { version = "1.0" }
bs58 = "0.4"
cfg-if = "1.0"

tracing = "0.1"

hex = "0.4"

sata = { git = "https://github.com/Satellite-im/Sata" }

chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
bs58 = "0.4"
warp-pd-flatfile = { path = "../warp-pd-flatfile" }
warp-pd-stretto = { path = "../warp-pd-stretto" }
rustyline-async = "0.2"
comfy-table = "6.0"
tracing-subscriber = "0.3"
clap = { version = "3.2", features = ["derive"] }

[features]
default = []
build-header = []
