[package]
name = "video-codec-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
clap = { version = "4.0", features=["derive"] }
tokio = { workspace = true }

av-data = { workspace = true }
eye = { workspace = true }
libaom = { workspace = true }
