[package]
name = "audio-kit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.4.0"
clap = { version = "4.0", features = ["derive"] }
cpal = "0.15.0"
log = { version = "0.4.17", features = ["std"]}
opus = "0.3.0"
ringbuf = "0.3.3"
simple_logger = "4.1.0"
tokio = { workspace = true, features = ["full"] }

anyhow.workspace = true
serde.workspace = true
once_cell.workspace = true